# Generated by Django 3.2.1 on 2023-06-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pendente'), (2, 'Análise Manual'), (3, 'Aprovado'), (4, 'Negado')], default=1),
        ),
    ]
