# Generated by Django 3.2.1 on 2023-06-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_proposta_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='formconfig',
            name='label',
            field=models.CharField(default='label', max_length=100, verbose_name='Label para exibição do campo'),
        ),
        migrations.AddField(
            model_name='formconfig',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Texto'), (2, 'E-mail'), (3, 'Inteiro')], default=1),
        ),
        migrations.AlterField(
            model_name='formconfig',
            name='campo',
            field=models.CharField(max_length=100, verbose_name='Nome do campo'),
        ),
        migrations.AlterField(
            model_name='formconfig',
            name='exibir',
            field=models.BooleanField(default=True),
        ),
    ]
