# Generated by Django 3.2.1 on 2023-06-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230617_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formconfig',
            name='tipo',
            field=models.IntegerField(choices=[('text', 'Texto'), ('email', 'Email'), ('number', 'Número')], default='text'),
        ),
    ]
