# Generated by Django 3.2.1 on 2023-06-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_formconfig_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formconfig',
            name='tipo',
            field=models.CharField(choices=[('text', 'text'), ('email', 'email'), ('number', 'number')], default='text', max_length=10),
        ),
    ]
