# Generated by Django 3.2.1 on 2023-06-17 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_formconfig_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formconfig',
            options={'verbose_name': 'Formulário campos', 'verbose_name_plural': 'Formulário campos'},
        ),
    ]
